### PR TITLE
Add transifex config

### LINKED ISSUE #1: Add transifex
@morrisjobke as discussed!

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #1

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@icewind1991 Please merge - I don't have push access to it or move the repo to the nextcloud org. Otherwise the nextcloud-bot also needs rights to push to this.

**Comment by MorrisJobke** [comment]
> @icewind1991 Please merge - I don't have push access to it or move the repo to the nextcloud org. Otherwise the nextcloud-bot also needs rights to push to this.

I already pushed the strings manually to transifex so the translation can start. For the down sync some permissions need to be fixed and this PR needs to be merged.

**Comment by rullzer** [comment]
Icewind moving the repo might be best right?

**Comment by icewind1991** [comment]
moved to the nc org

**Pull request merged**
